### ISSUE TITLE
Create Hero Slide content type and Entityqueue

### ISSUE THREAD

**Issue by leo72** [drupalAM/drupal-am#3]
Hero Slide CT fields:

- Title prefix (textfield)
- Title (textfield *)
- Body and Summary (Body with Summary)
- Hero Image (Image *)
- Text Position (List with "left", "center", "right" values)
- Images (Image (multivalue))
- Show link to content (Bool (default TRUE))
- External Link (Link with Title)

"Homepage Hero Slider" Entityqueue:

- Content Type:  Hero Slide
- Number of items: Unlimited
- Min number of items: 1

**Comment by angela-G** [comment]
Hero Slide content type
http://dev.drupal.am/node/add/hero_slide

Homepage Hero Slider entityqueue
http://dev.drupal.am/admin/structure/entityqueue/homepage_hero_slider/homepage_hero_slider
