### ISSUE TITLE
Upgrade site to Drupal 9

### ISSUE THREAD

**Issue by muradyanani** [drupalAM/drupal-am#52]

**Comment by levmyshkin** [comment]
Hi @leo72, Drupal environment is needed for PHP GD2 library:

![Screenshot from 2022-04-29 15-55-00](https://user-images.githubusercontent.com/1680925/165939642-f3c0b8f3-b23f-45f0-81c6-8905cb4ed5ee.png)

Build process failed cause of missing library.
