### ISSUE TITLE
Create Company CT

### ISSUE THREAD

**Issue by muradyanani** [drupalAM/drupal-am#83]
Connect with the user during the registration
Add a dropdown with employees quantity: 0-5, 5-15… (dropdown without text)

Fields:
- Title
- Image
- URL (website)
- Employees quantity

**Comment by levmyshkin** [comment]
Added Company content type in this pull request:
https://github.com/drupalAM/drupal-am/pull/93

**Comment by levmyshkin** [comment]
Added Company content type on Dev:
https://dev.drupal.am/en/node/17
I will update image field with media field on another ticket.
